baseURL = "https://blog.raspikidd.com"
languageCode = "en-gb"
title = "RaspiKidd Blog"
theme = "base16"
paginate = 10000

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    title = "RaspiKidd"
    slogan = "Making programming fun through physical computing"
    SEOTitle = "RaspiKidd blog"
    keywords = "Kerry, Kidd, RaspberryPi, RaspiKidd, EduKidd, microbit, prgramming, coding, electronics, robots, robotics, Python, MicroPython, MakeCode, scratch"
